version: '2'
services:
  app:
    build: .
    entrypoint: ./bin/wait_for_pg.sh db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env.test
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ''
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432"
